import re

with open('src/export_to_c.py', 'r') as f:
    content = f.read()

header_gen_code = """
    # =========================================================
    # DYNAMIC C FEATURES GENERATOR (COMPTIME METAPROGRAMMING)
    # =========================================================
    feature_names = rf.feature_names_in_
    header_path = os.path.join(out_dir, "iot_shield_features.h")
    
    with open(header_path, "w") as hf:
        hf.write("// =========================================================================\\n")
        hf.write("// AUTO-GENERATED BY EXPORT_TO_C.PY\\n")
        hf.write("// Dynamic Feature Mapping (Comptime)\\n")
        hf.write("// =========================================================================\\n\\n")
        hf.write("#ifndef IOT_SHIELD_FEATURES_H\\n")
        hf.write("#define IOT_SHIELD_FEATURES_H\\n\\n")
        
        # Macros enabling specific features
        hf.write("// Enabling compilation flags for DCE (Dead Code Elimination)\\n")
        for fn in feature_names:
            safe_fn = fn.upper()
            hf.write(f"#define FEATURE_{safe_fn}\\n")
            
        hf.write("\\n")
        hf.write("// Inline function that pulls from C struct to array in the EXACT Python order\\n")
        hf.write("static inline void populate_ml_array(FlowRecord *f, double *input, double dur_sec) {\\n")
        hf.write("    int idx = 0;\\n")
        
        for fn in feature_names:
            safe_fn = fn.upper()
            hf.write(f"#ifdef FEATURE_{safe_fn}\\n")
            
            # Map Python name to C struct access
            if fn == "src_port": hf.write("    input[idx++] = f->key.src_port;\\n")
            elif fn == "dst_port": hf.write("    input[idx++] = f->key.dst_port;\\n")
            elif fn == "protocol": hf.write("    input[idx++] = f->key.protocol;\\n")
            elif fn == "duration_ms": hf.write("    input[idx++] = f->duration_ms;\\n")
            elif fn == "bidirectional_packets": hf.write("    input[idx++] = f->src2dst.packets + f->dst2src.packets;\\n")
            
            # src2dst stats
            elif fn == "src2dst_duration_ms": hf.write("    input[idx++] = f->src2dst.duration_ms;\\n")
            elif fn == "src2dst_packets": hf.write("    input[idx++] = f->src2dst.packets;\\n")
            elif fn == "src2dst_bytes": hf.write("    input[idx++] = f->src2dst.bytes;\\n")
            elif fn == "src2dst_syn_packets": hf.write("    input[idx++] = f->src2dst.syn_packets;\\n")
            elif fn == "src2dst_rst_packets": hf.write("    input[idx++] = f->src2dst.rst_packets;\\n")
            elif fn == "src2dst_concurrent_flows": hf.write("    input[idx++] = f->src2dst_concurrent_flows;\\n")
            
            # dst2src stats
            elif fn == "dst2src_duration_ms": hf.write("    input[idx++] = f->dst2src.duration_ms;\\n")
            elif fn == "dst2src_packets": hf.write("    input[idx++] = f->dst2src.packets;\\n")
            elif fn == "dst2src_bytes": hf.write("    input[idx++] = f->dst2src.bytes;\\n")
            elif fn == "dst2src_syn_packets": hf.write("    input[idx++] = f->dst2src.syn_packets;\\n")
            elif fn == "dst2src_rst_packets": hf.write("    input[idx++] = f->dst2src.rst_packets;\\n")
            elif fn == "dst2src_concurrent_flows": hf.write("    input[idx++] = f->dst2src_concurrent_flows;\\n")
            
            # Packets Sizes (Min/Max/Mean/Std)
            elif fn == "src2dst_min_ps": hf.write("    input[idx++] = f->src2dst.min_ps;\\n")
            elif fn == "src2dst_max_ps": hf.write("    input[idx++] = f->src2dst.max_ps;\\n")
            elif fn == "src2dst_mean_ps": hf.write("    input[idx++] = f->src2dst.packets > 0 ? (double)f->src2dst.sum_ps / f->src2dst.packets : 0;\\n")
            elif fn == "src2dst_stddev_ps": hf.write("    input[idx++] = calc_stddev(f->src2dst.sum_ps, f->src2dst.sum_sq_ps, f->src2dst.packets);\\n")
            
            elif fn == "dst2src_min_ps": hf.write("    input[idx++] = f->dst2src.min_ps;\\n")
            elif fn == "dst2src_max_ps": hf.write("    input[idx++] = f->dst2src.max_ps;\\n")
            elif fn == "dst2src_mean_ps": hf.write("    input[idx++] = f->dst2src.packets > 0 ? (double)f->dst2src.sum_ps / f->dst2src.packets : 0;\\n")
            elif fn == "dst2src_stddev_ps": hf.write("    input[idx++] = calc_stddev(f->dst2src.sum_ps, f->dst2src.sum_sq_ps, f->dst2src.packets);\\n")
            
            # PIATs
            elif fn == "src2dst_min_piat_ms": hf.write("    input[idx++] = f->src2dst.min_piat_ms;\\n")
            elif fn == "src2dst_max_piat_ms": hf.write("    input[idx++] = f->src2dst.max_piat_ms;\\n")
            elif fn == "src2dst_mean_piat_ms": hf.write("    input[idx++] = f->src2dst.packets > 1 ? f->src2dst.sum_piat / (f->src2dst.packets - 1) : 0;\\n")
            elif fn == "src2dst_stddev_piat_ms": hf.write("    input[idx++] = calc_stddev(f->src2dst.sum_piat, f->src2dst.sum_sq_piat, f->src2dst.packets > 1 ? f->src2dst.packets - 1 : 0);\\n")
            
            elif fn == "dst2src_min_piat_ms": hf.write("    input[idx++] = f->dst2src.min_piat_ms;\\n")
            elif fn == "dst2src_max_piat_ms": hf.write("    input[idx++] = f->dst2src.max_piat_ms;\\n")
            elif fn == "dst2src_mean_piat_ms": hf.write("    input[idx++] = f->dst2src.packets > 1 ? f->dst2src.sum_piat / (f->dst2src.packets - 1) : 0;\\n")
            elif fn == "dst2src_stddev_piat_ms": hf.write("    input[idx++] = calc_stddev(f->dst2src.sum_piat, f->dst2src.sum_sq_piat, f->dst2src.packets > 1 ? f->dst2src.packets - 1 : 0);\\n")
            
            # Engineered Features
            elif fn == "is_constant_payload": hf.write("    double s2d_std_ps = calc_stddev(f->src2dst.sum_ps, f->src2dst.sum_sq_ps, f->src2dst.packets); input[idx++] = (s2d_std_ps < 1.0) ? 1.0 : 0.0;\\n")
            elif fn == "src2dst_flow_rate": hf.write("    double r = f->src2dst.packets / dur_sec; input[idx++] = r > 2000.0 ? 2000.0 : r;\\n")
            elif fn == "in_out_packet_ratio": hf.write("    double d_p = f->dst2src.packets == 0 ? 1.0 : f->dst2src.packets; double rat = f->src2dst.packets / d_p; input[idx++] = rat > 100.0 ? 100.0 : rat;\\n")
            elif fn == "syn_to_total_ratio": hf.write("    double s_p = f->src2dst.packets == 0 ? 1.0 : f->src2dst.packets; input[idx++] = f->src2dst.syn_packets / s_p;\\n")
            elif fn == "is_discovery_protocol": hf.write("    input[idx++] = (f->key.protocol == 17 && (f->key.dst_port == 1900 || f->key.dst_port == 5353 || f->key.dst_port == 137 || f->key.dst_port == 138 || f->key.dst_port == 67 || f->key.dst_port == 68)) ? 1.0 : 0.0;\\n")
            
            else:
                hf.write(f"    input[idx++] = 0.0; // Feature {fn} was not natively mapped in comptime!\\n")
                
            hf.write(f"#endif\\n")
            
        hf.write("}\\n\\n")
        hf.write("#endif // IOT_SHIELD_FEATURES_H\\n")
"""

content = content.replace("with open(os.path.join(out_dir, 'iot_shield_model.c'), 'w') as f:", header_gen_code + "\\n    with open(os.path.join(out_dir, 'iot_shield_model.c'), 'w') as f:")

with open('src/export_to_c.py', 'w') as f:
    f.write(content)
